export const nav = [['About Us','/about'],['Industries','/industries'],['Our Services','/services'],['Why Choose Us','/why-oryenza'],['Our Process','/process'],['Contact Us','/contact']];
export const intro = 'Oryenza Talent Services is a modern recruitment and talent solutions company focused on connecting the right talent with the right opportunities across India and global markets.';
export const services = [
 {title:'Permanent Recruitment',description:'End-to-end hiring solutions for full-time positions across IT and Non-IT functions.',items:['IT Recruitment','Non-IT Recruitment','Professional & Specialist Hiring','Mid-Level Hiring','Senior-Level Hiring']},
 {title:'Contract & Temporary Staffing',description:'Flexible staffing solutions to meet short-term, project-based, or time-bound business requirements.',items:['Contract Staffing','Temporary Staffing','Project-Based Hiring','Contract-to-Hire','Workforce Augmentation']},
 {title:'Executive & Leadership Search',description:'Confidential and targeted search for senior leaders and critical positions that drive business success.',items:['Executive Search','CXO Hiring','Leadership Hiring','Senior Management Hiring','Confidential Search','Specialized Leadership Recruitment']},
 {title:'Volume & Specialized Hiring',description:'Scalable hiring solutions for high-volume and niche skill requirements.',items:['Bulk / Volume Hiring','Mass Recruitment Drives','Campus / Graduate Hiring','Niche Skill Hiring','Hard-to-Fill Positions','Urgent / Priority Hiring']},
 {title:'Global & Cross-Border Recruitment',description:'Connecting talent across borders to support your growth globally.',items:['Domestic Recruitment (India)','International Recruitment','Global Talent Acquisition','Remote / Distributed Team Hiring','Cross-Border Talent Search']}
];
export const industries = [
 ['IT & Technology','Delivering top tech talent for innovative and digital-first businesses.'],['Banking, Financial Services & Insurance','Powering growth in finance, insurance, and investment.'],['Healthcare & Life Sciences','Enabling better healthcare through talent and innovation.'],['Manufacturing & Engineering','Building technology, infrastructure, and industrial excellence.'],['E-Commerce & Retail','Driving digital commerce and customer experiences.'],['Automotive & Mobility','Accelerating innovation in automotive design, EV, and mobility.'],['Semiconductor & Electronics','Supporting chip design, embedded systems, and advanced electronics.'],['IoT & Robotics','Connecting devices and automating the future with smart solutions.'],['Telecommunications','Enabling connectivity and communication for a smarter world.'],['Logistics & Supply Chain','Driving efficiency and seamless operations across the globe.'],['Education & E-Learning','Shaping the future through knowledge and learning.'],['Travel, Hospitality & Aviation','Connecting people and experiences worldwide.'],['Media, Entertainment & Advertising','Fueling creativity, engagement, and brand impact.'],['Energy & Utilities','Powering businesses with sustainable energy and utilities.'],['Public Sector & Government','Supporting nation-building through skilled and dedicated talent.'],['Consulting & Professional Services','Driving strategy, transformation, and business success.'],['Agriculture & Agri-Tech','Cultivating growth through innovation and technology.'],['Cybersecurity','Protecting businesses with top security talent and expertise.'],['Cloud & SaaS','Enabling scalable solutions in the cloud era.'],['Biotechnology','Advancing research and innovation for a better tomorrow.'],['Real Estate & Construction','Building spaces and communities for the future.']
];
export const advantages = [
 ['AI-Powered Sourcing & Screening','We use advanced, technology-based tools for intelligent sourcing and smart screening, so that only the most relevant and high-quality candidates reach you.'],['Industry Knowledge & Market Insights','Before we start, our team understands your industry, conducts market research, and provides salary benchmarks to define the right hiring strategy.'],['IT & Non-IT Expertise','Strong expertise across IT, Engineering, Core, Corporate Functions, and diverse Non-IT domains, ensuring the right talent for every role.'],['Domestic & Global Reach','PAN India presence with a global talent network, enabling us to connect clients with the right talent anytime, anywhere.'],['Large Talent Pool & Structured Systems','We maintain a large, well-segmented talent database across industries and locations, managed through our structured systems for speed and accuracy.'],['End-to-End Recruitment Support','From requirement understanding to final joining, we handle everything, including sourcing, screening, shortlisting, interviews, coordination, and negotiation.']
];
export const steps = [
 ['Partner','Agreement and alignment. Terms are agreed, scope of services is finalized, and key points of contact are confirmed.'],['Onboard',"A welcome and kick-off stage where we understand the client's business, goals, hiring plans, and communication preferences."],['Understand',"We align with the client's company policy, work culture, and team environment, and build an in-depth understanding of the requirement and job description."],['Research','Industry and market intelligence, including talent market research, competitor hiring insights, and salary benchmarking, to define the right hiring strategy.'],['Source','We tap into our large talent pool and sourcing network, using a strong pipeline approach across India and global markets.'],['Evaluate','Careful screening and human validation for skills, experience, communication, and cultural fit, so only the right candidates move forward.'],['Select','Shortlisted candidates are presented with detailed profiles, followed by interview coordination, feedback management, and support through offer and negotiation.'],['Join & Support','Continuous communication until the candidate joins, along with joining coordination, documentation support, and post-joining follow-up.']
];
export const values = [['Integrity','We operate with honesty, transparency, and fairness in everything we do.'],['People First','We value people, respect diversity, and believe in creating meaningful opportunities.'],['Excellence','We deliver quality through expertise, innovation, and a commitment to continuous improvement.'],['Partnership','We build long-term partnerships based on trust, collaboration, and shared success.'],['Innovation','We embrace technology and new ideas to deliver smarter and faster hiring solutions.'],['Accountability','We take ownership, meet commitments, and strive for measurable results.']];
