import Link from 'next/link';
import {ArrowUpRight, Globe2, Users, BriefcaseBusiness, Building2, Cpu, HeartPulse, Landmark, Factory, ShoppingBag, GraduationCap, ShieldCheck, Target, Sparkles, Handshake, Check, Search, UserCheck, Network} from 'lucide-react';
import {intro,services,industries,advantages} from './data';
import {Button,CTA,FAQ} from './ui';
const serviceIcons=[Users,BriefcaseBusiness,Search,UserCheck,Globe2];
const industryIcons=[Cpu,Landmark,HeartPulse,Factory,ShoppingBag,GraduationCap];
function TalentVisual(){return <div className="talent-visual" aria-label="A connected network of professionals"><div className="radial-lines"/><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="network-core"><img src="/images/mark.png" alt="Oryenza"/></div>{[0,1,2,3,4,5,6,7,8,9,10,11].map((n)=><div key={n} className={`person person-${n}`}><img src={`/images/person-${n%6}.jpg`} alt=""/><span><Check size={9}/></span></div>)}<div className="floating-chip chip-top"><span><Cpu size={18}/></span>IT & Technology</div><div className="floating-chip chip-bottom"><span><UserCheck size={18}/></span>The right talent. The right fit.</div><div className="location location-one"><span/>India</div><div className="location location-two"><span/>Global reach</div></div>}
export default function Home(){return <><section className="hero"><div className="container hero-grid"><div className="hero-copy"><div className="hero-badge"><span/>YOUR PARTNER IN PEOPLE & GROWTH</div><h1>We don’t just<br/>fill positions.<br/>We build <span>winning teams.</span></h1><p>{intro}</p><div className="hero-actions"><Button href="/contact">Win with the right hire</Button><Link href="/services" className="text-link">Explore our services<ArrowUpRight size={17}/></Link></div><div className="hero-trust"><ShieldCheck size={17}/> People first. Quality always. India & beyond.</div></div><TalentVisual/></div><div className="hero-bottom">SMART RECRUITMENT. HUMAN EXPERTISE. REAL IMPACT.<span>Scroll to explore ↓</span></div></section>
<section className="container metrics reveal"><div className="metric-heading"><span className="eyebrow">GROWING TOGETHER</span><h2>People behind<br/>the progress.</h2></div>{[['25+','Happy clients',Handshake],['15+','Industries served',Building2],['500+','Successful placements',UserCheck],['Global','India & beyond',Globe2]].map(([value,label,Icon])=>{const I=Icon as typeof Users;return <div className="metric" key={String(label)}><I/><strong>{String(value)}</strong><span>{String(label)}</span></div>})}</section>
<section className="section services-section"><div className="container"><div className="section-heading reveal"><div><span className="eyebrow">TAILORED TO YOUR AMBITION</span><h2>The right people.<br/><span>The right solutions.</span></h2></div><p>From your next great hire to your next phase of growth, we help you build a team that moves your business forward.</p></div><div className="service-grid">{services.map((s,i)=>{const Icon=serviceIcons[i];return <Link href={`/services#service-${i}`} key={s.title} className="service-card reveal"><span className="icon-box"><Icon size={26}/></span><span className="card-number">0{i+1}</span><h3>{s.title}</h3><p>{s.description}</p><span className="card-link">Explore solution<ArrowUpRight size={20}/></span></Link>})}</div></div></section>
<section className="section"><div className="container about-grid"><div className="about-art reveal"><img src="/images/team.jpg" alt="Professionals collaborating on a hiring strategy"/><div className="about-quote"><span>OUR BELIEF</span><h3>Great people.<br/>Great possibilities.</h3><span className="quote-arrow">↗</span></div><div className="photo-label"><span/>Connecting talent. Creating impact.</div></div><div className="about-copy reveal"><span className="eyebrow">MEET ORYENZA</span><h2>More than hiring.<br/><span>A partnership<br/>for growth.</span></h2><p>We specialize in IT and Non-IT hiring, domestic and global recruitment, and tailored talent solutions across industries.</p><p>Our approach combines smart recruitment tools, strong talent sourcing, market intelligence, and human expertise to connect organizations with high-quality professionals.</p><div className="check-row"><Check/>Built on trust, driven by people</div><div className="check-row"><Check/>Smart technology meets human expertise</div><Button href="/about" secondary>Get to know us</Button></div></div></section>
<section className="section process-preview"><div className="container"><div className="section-heading reveal"><div><span className="eyebrow">THE ORYENZA TALENT JOURNEY</span><h2>Great hires don’t happen<br/>by chance. <span>They happen by design.</span></h2></div><Button href="/process" secondary>Our complete process</Button></div><div className="process-grid">{[['01','Understand & align','We get to know your business, culture, and goals. Then we research the market and build your hiring strategy.',Handshake],['02','Source & evaluate','Smart sourcing and human validation bring the most relevant talent into focus.',Search],['03','Select, join & support','From the first interview to the first day and beyond, we stay with you every step of the way.',UserCheck]].map(([n,t,d,I])=>{const Icon=I as typeof Users;return <div className="process-card reveal" key={String(n)}><span className="step-number">{String(n)}</span><div className="process-icon"><Icon size={42}/></div><h3>{String(t)}</h3><p>{String(d)}</p></div>})}</div></div></section>
<section className="section industries-section"><div className="container"><div className="section-heading reveal"><div><span className="eyebrow">EXPERTISE WITHOUT BOUNDARIES</span><h2>Your industry.<br/><span>Our understanding.</span></h2></div><div><p>Talent solutions built around your world. Connecting businesses with the expertise they need across India and global markets.</p><Link className="text-link" href="/industries">View all industries<ArrowUpRight size={18}/></Link></div></div><div className="industry-grid">{[0,1,2,3,4,10].map((n,i)=>{const Icon=industryIcons[i];return <Link href="/industries" className="industry-card reveal" key={n}><Icon/><h3>{industries[n][0]}</h3><ArrowUpRight size={18}/></Link>})}</div></div></section>
<section className="section advantage-section"><div className="container advantage-grid"><div className="reveal"><span className="eyebrow">THE ORYENZA ADVANTAGE</span><h2>Technology.<br/>Expertise.<br/><span>Commitment.</span></h2><p>We combine technology, expertise, and a structured approach to deliver high-quality hires that create real impact for your business.</p><Button href="/why-oryenza">Why choose Oryenza</Button><div className="advantage-seal"><img src="/images/mark.png" alt=""/><span>WIN WITH<br/>THE RIGHT HIRE</span></div></div><div className="advantages">{[advantages[0],advantages[2],advantages[3],advantages[5]].map(([t,d],i)=><div key={t} className="advantage-item reveal"><span>0{i+1}</span><div><h3>{t}</h3><p>{d}</p></div><ArrowUpRight size={20}/></div>)}</div></div></section>
<section className="container focus-strip reveal">{[['Our Focus','Deliver the right talent solutions that drive business growth and performance.'],['Our Expertise','Deep industry knowledge, smart sourcing, and a rigorous evaluation process.'],['Our Commitment','Quality, integrity, and transparency in every engagement.'],['Our Impact','Empowering organizations with the right talent to achieve their goals.']].map(([t,d])=><div key={t}><Sparkles size={20}/><h3>{t}</h3><p>{d}</p></div>)}</section>
<section className="section"><div className="container faq-grid"><div className="reveal"><span className="eyebrow">A LITTLE MORE CLARITY</span><h2>Your questions.<br/><span>Answered.</span></h2><p>Want to know more about working with us?</p><Link href="/contact" className="text-link">Let’s have a conversation<ArrowUpRight size={18}/></Link></div><FAQ/></div></section><CTA/></>}
