'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {usePathname} from 'next/navigation';
import {ArrowUpRight, ArrowRight, Menu, X, Mail, Phone, MapPin, Check, Plus, ChevronUp} from 'lucide-react';
import {nav} from './data';
export function Header(){const [open,setOpen]=useState(false);const path=usePathname();useEffect(()=>setOpen(false),[path]);return <header className="header"><div className="nav-wrap"><Link href="/" className="brand" aria-label="Oryenza home"><img src="/images/mark.png" alt=""/><span>ORY<span className="brand-blue">E</span>NZA<small>TALENT SERVICES</small></span></Link><button className="menu-toggle" onClick={()=>setOpen(!open)} aria-expanded={open} aria-label="Toggle navigation">{open?<X/>:<Menu/>}</button><nav className={open?'navigation open':'navigation'}>{nav.map(([label,url])=><Link className={`${path===url?'active ':''}${url==='/contact'?'nav-contact':''}`} key={url} href={url}>{label}{url==='/contact'&&<ArrowUpRight size={16}/>}</Link>)}</nav></div></header>}
export function Footer(){return <footer><div className="container footer-grid"><div><Link href="/" className="brand"><img src="/images/mark.png" alt=""/><span>ORYENZA<small>TALENT SERVICES</small></span></Link><p className="footer-tagline">Win With the Right Hire</p><p>Connecting exceptional people with exceptional opportunities. India & beyond.</p></div><div><h4>Explore Oryenza</h4><Link href="/">Home</Link>{nav.map(([l,u])=><Link key={u} href={u}>{l}</Link>)}</div><div><h4>Let’s connect</h4><a href="mailto:info@oryenza.in">info@oryenza.in</a><a href="mailto:careers@oryenza.in">careers@oryenza.in <small>Careers</small></a><a href="mailto:sales@oryenza.in">sales@oryenza.in <small>Sales</small></a><a href="tel:+918200057027">+91 82000 57027</a><p>B-904, Pragati IT Park, Opp. Shell Petrol Pump, Mota Varachha, Surat, Gujarat – 394101</p></div></div><div className="container footer-bottom"><span>© 2026 Oryenza Talent Services. All rights reserved.</span><span>People. Potential. Possibilities.</span></div></footer>}
export function Effects(){const path=usePathname();const [top,setTop]=useState(false);useEffect(()=>{document.documentElement.classList.add('js-reveals');const obs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');obs.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(e=>obs.observe(e));const scroll=()=>setTop(window.scrollY>650);window.addEventListener('scroll',scroll);return()=>{obs.disconnect();window.removeEventListener('scroll',scroll)}},[path]);return top?<button className="back-top" onClick={()=>window.scrollTo({top:0,behavior:'smooth'})} aria-label="Back to top"><ChevronUp/></button>:null}
export function Button({href,children,secondary=false}:{href:string,children:React.ReactNode,secondary?:boolean}){return <Link href={href} className={secondary?'button secondary':'button'}>{children}<ArrowUpRight size={18}/></Link>}
export function CTA(){return <section className="container cta reveal"><div><span className="eyebrow">LET’S BUILD WHAT’S NEXT</span><h2>Looking for the right talent,<br/>or the right opportunity?</h2><p>Let’s talk. Together, let’s build the future with the right talent.</p></div><Button href="/contact">Get in touch</Button><div className="cta-orbit"/></section>}
export function PageHero({eyebrow,title,description}:{eyebrow:string,title:string,description:string}){return <section className="page-hero"><div className="container"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p><div className="breadcrumb"><Link href="/">Home</Link><ArrowRight size={14}/><span>{eyebrow}</span></div></div><div className="page-decoration"/></section>}
export function FAQ(){const questions=[['What recruitment services does Oryenza offer?','We offer permanent recruitment, contract and temporary staffing, executive and leadership search, volume and specialized hiring, and global and cross-border recruitment.'],['Do you hire for both IT and Non-IT roles?','Yes. Our expertise spans IT, Engineering, Core, Corporate Functions, and diverse Non-IT domains across a wide range of industries.'],['Can you support hiring outside India?','Yes. We combine PAN India presence with a global talent network to support international, cross-border, remote, and distributed team hiring.'],['Will we have a dedicated point of contact?','Every client is assigned a dedicated Hiring Manager who understands their requirements and manages the process from requirement to joining.'],['How can I apply for a job?','Send your profile to careers@oryenza.in or select Job Application on our contact form. Our team will connect with you about relevant opportunities.']];return <div className="faq-list">{questions.map(([q,a])=><details key={q}><summary>{q}<Plus size={20}/></summary><p>{a}</p></details>)}</div>}
export function ContactForm(){const [status,setStatus]=useState('');return <form className="contact-form" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);const reason=String(d.get('reason'));const recipient=reason==='Job Application'?'careers@oryenza.in':reason==='Sales Enquiry'?'sales@oryenza.in':'info@oryenza.in';const body=`Name: ${d.get('name')}\nCompany: ${d.get('company')}\nEmail: ${d.get('email')}\nPhone: ${d.get('phone')}\n\n${d.get('message')}`;window.location.href=`mailto:${recipient}?subject=${encodeURIComponent(reason+' — '+d.get('name'))}&body=${encodeURIComponent(body)}`;setStatus('Your email draft is ready in your email app. Please send it to complete your enquiry.')}}><h2>Tell us what you’re looking for.</h2><p>Start a conversation. We’re here to help.</p><div className="form-grid"><label>Full name <span>*</span><input name="name" required autoComplete="name" placeholder="Your full name"/></label><label>Company name<input name="company" autoComplete="organization" placeholder="Your company"/></label><label>Email address <span>*</span><input name="email" type="email" required autoComplete="email" placeholder="you@company.com"/></label><label>Phone number<input name="phone" type="tel" autoComplete="tel" placeholder="+91"/></label></div><label>Reason for contact<select name="reason"><option>Sales Enquiry</option><option>Job Application</option><option>General Enquiry</option></select></label><label>Message / Requirement details <span>*</span><textarea name="message" required rows={5} placeholder="Tell us about your hiring needs or the opportunity you’re seeking…"/></label><button className="button" type="submit">Prepare enquiry email<ArrowUpRight size={18}/></button><small className="form-note">Opens your email app with your enquiry addressed to the right team.</small><p role="status" className="form-status">{status}</p></form>}
